# Generated by Django 5.1.6 on 2025-02-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='semicategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
