# Generated by Django 5.1.6 on 2025-02-14 09:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_saleitem_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date_issued',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
